#-------------------------------
# General Site Settings

title: Louis BOUDDHOU
description: Junior Web Developer / Front End Developer
email: louis.bouddhou@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Me, url: '#me'}
- {name: Projects, url: '#projects'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section



#-------------------------------
# Projects Section

projects:
- {name: 'Apt Abode', folder: 'project1', category: 'category-1', data-order: '1'}
- {name: "Font'N", folder: 'project2', category: 'category-2', data-order: '2'}
- {name: "Quikst", folder: 'project3', category: 'category-3', data-order: '3'}
- {name: "myCUplanner", folder: 'project4', category: 'category-1', data-order: '4'}
- {name: "Perfect Packed Suitcase", folder: 'project5', category: 'category-3', data-order: '5'}
- {name: "The Fountain", folder: 'project6', category: 'category-4', data-order: '6'}
- {name: 'Webfolio', folder: 'project7', category: 'category-1', data-order: '7'}
- {name: "City Night Rides", folder: 'project8', category: 'category-4', data-order: '8'}



#- {name: Project 2, folder: 'proj-2', file: 'work/proj-2.html'}
#- {name: Project 3, folder: 'proj-3', file: 'work/proj-3.html'}
#- {name: Project 4, folder: 'proj-4', file: 'work/proj-4.html'}
#- {name: Project 5, folder: 'proj-5', file: 'work/proj-5.html'}
#- {name: Project 6, folder: 'proj-6', file: 'work/proj-6.html'}
#- {name: Project 7, folder: 'proj-7', file: 'work/proj-7.html'}
#- {name: Project 8, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Events Section

experiences:
- {company: DragonDev,
  location: Boulder,
  state: CO,
  role: Junior Web Application Developer,
  work1: Improving user-friendliness of one of the company’s web app tools and updating the interface to follow the company’s standards.,
  work2: Building a mobile web application for a company’s client and helped fixing bugs on other web applications.,
  time: September 2013 - May 2014,
  classname: timeline
}

- {company: ASCE National Student Steel Bridge Competition,
location: Boulder,
state: CO,
role: Bridge Constructor,
work1: Helped fabricate a one-tenth scale steel bridge as part of a team of students at the University of Colorado Boulder.,
work2: Practiced structural design/analysis and project management and learned fabrication techniques while gaining appreciation for the strength and constructability of steel.,
time: February 2013 - April 2014,
classname: timeline-inverted
}

- {company: Water Waste Issue (class project),
location: Boulder,
state: CO,
role: Group Project Member,
work1: Analyzed water waste issues in Williams Village as member of the Residential Academic Program (RAP). Project exhibited at the yearly science expo,
work2: Collected data on water distribution in Williams Village housing facilities (part of CU campus) and assessed residents’ clean water usage through conducted surveys.,
work3: Designed a water-efficient facility system to help conserve clean water used by students through the use of grey water and sustainable water-consumption.,
time: October 2011 - December 2011,
classname: timeline
}

- {company: Chemical Lab Experiments,
location: Libreville,
state: GABON,
role: Participant,
work1: Conducted weekly high-school advanced chemistry lab experiments in preparation for the French national yearly contest the ‘Olympiades de Chimie’ (chemistry Olympics) in Blaise Pascal High School over 45 hours in total on the course of 3 months.,
time: October 2011 - December 2011,
classname: timeline-inverted
}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
